apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: vote
  labels:
    name: db-deployment
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db-app-pod
      app: demo-app
  template:
    metadata:
      name: db-app-pod
      labels:
        name: db-app-pod
        app: demo-app
    spec:
      containers:
        - name: db
          image: postgres:9.4
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
       volumn:
         - name: db-data
           emptyDir: {}
       
