apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: vote
  labels:
    name: db-service
    app: demo-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: db-app-pod
    app: demo-app
