apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  namespace: vote
  labels:
    name: result-deployment
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app-pod
      app: demo-app
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: demo-app
    spec:
      containers:
        - name: result-app-pod
          image: kodekloud/examplevotingapp_result:before
          ports:
            - containerPort: 80
